# In order to build for staging run:
# $ jekyll build --config _config.yml, _config-staging.yml
#
# URL of static site
url: "https://staging.96boards.org"
# Destination folder
destination: staging.96boards.org
# Production boolean used in layouts / includes
production: false
# Google Analytics
google_analytics:
  enabled: false
  code: GTM-P53JPC
